### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by SuHyeonEo** [SuHyeonEo/first-repository#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Entity 클래스 정의
2. [ ] Dto 클래스 작성
3. [ ] Mapper 클랙스 작성
4. [ ] Controller 클래스 작성(PostMapping)
5. [ ] Service 클래스 작성

### 예상 작업 시간
3h
